version: '3.9'

services:
#  db:
#    image: postgres:17
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
#    depends_on:
#      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/staticfiles:ro
      - ./media:/media:ro
    depends_on:
      - web

#volumes:
#  pgdata:
